services:
  mcp-db:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgresql://mcp:password@db:5432/mcp
      ALLOW_WRITES: "false"
      ALLOW_DDL: "false"
      MAX_ROWS: "500"
      QUERY_TIMEOUT_SEC: "20"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mcp
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mcp
      MYSQL_USER: mcp
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  mariadb:
    image: mariadb:11.2
    environment:
      MARIADB_DATABASE: mcp
      MARIADB_USER: mcp
      MARIADB_PASSWORD: password
      MARIADB_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
