services:
  mcp-db:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: postgresql://mcp:password@db:5432/mcp
      ALLOW_WRITES: "false"
      ALLOW_DDL: "false"
      MAX_ROWS: "500"
      QUERY_TIMEOUT_SEC: "20"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mcp
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
